apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: iamvishalnair-com-tls
spec:
  secretName: iamvishalnair-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: iamvishalnair.com
  dnsNames:
    - iamvishalnair.com
    - www.iamvishalnair.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - iamvishalnair.com
          - www.iamvishalnair.com