apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name:  letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'vishal.vijayan@live.com'
    privateKeySecretRef:
      name:  letsencrypt-prod
    http01: {}
